version: '3'

services:
    nginx:
        container_name: veloservice-nginx
        image: nginx:stable
        ports:
            - "127.0.0.1:80:80"
        volumes:
            - .:/var/www:delegated
            - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
        networks:
            - default

    php:
        container_name: veloservice-php
        build:
            context: .docker/images/php
            dockerfile: Dockerfile
        volumes:
            - .:/var/www:delegated
        ports:
            - "127.0.0.1:9000:9000"
        networks:
            - default
        working_dir: /var/www

    mysql:
        container_name: veloservice-mysql
        image: mysql:8
        restart: unless-stopped
        tty: true
        ports:
            - "127.0.0.1:3306:3306"
        environment:
            MYSQL_HOST: localhost
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - default
        volumes:
            - mysql:/var/lib/mysql

volumes:
    mysql:
        driver: local
